commit2_dev

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,16 +1,4 @@
 #!/bin/sh
-echo "Starting Unit testing"
-./gradlew test
-# Capture the exit code of the previous command
-test_exit_code=$?
-# Check if Ktlint found errors
-if [ $test_exit_code -ne 0 ]; then
-    echo "Test Errors"
-    exit 1
-fi
-# If no errors were found, allow the commit
-exit 0
-
 echo "Starting Ktlint"
 
 # Run Ktlint to check for code style errors
@@ -24,3 +12,16 @@ if [ $ktlint_exit_code -ne 0 ]; then
 fi
 # If no errors were found, allow the commit
 exit 0
+
+echo "Starting Unit testing"
+./gradlew test
+# Capture the exit code of the previous command
+test_exit_code=$?
+# Check if Ktlint found errors
+if [ $test_exit_code -ne 0 ]; then
+    echo "Test Errors"
+    exit 1
+fi
+# If no errors were found, allow the commit
+exit 0
+
