commit

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -3,9 +3,19 @@
 ./gradlew ktlintFormat
 # Capture the exit code of the previous command
 ktlint_exit_code=$?
-echo "CODE ="$ktlint_exit_code
 # Check if Ktlint found errors
 if [ $ktlint_exit_code -ne 0 ]; then
+    echo "Ktlint found errors. Commit aborted."
+    exit 1
+fi
+# If no errors were found, allow the commit
+exit 0
+
+./gradlew test
+# Capture the exit code of the previous command
+test_exit_code=$?
+# Check if Ktlint found errors
+if [ $test_exit_code -ne 0 ]; then
     echo "Ktlint found errors. Commit aborted."
     exit 1
 fi
