hello

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,9 +1,13 @@
-#!/bin/sh
-
-# Check for code style violations with ktlint
-echo "Running git pre-commit hook"
+#!/bin/bash
+# Run Ktlint to check for code style errors
 ./gradlew ktlintFormat
-STATUS=$?
-# return 1 exit code if running checks fails
-[ $STATUS -ne 0 ] && exit 1
+# Capture the exit code of the previous command
+ktlint_exit_code=$?
+echo "CODEE ="$ktlint_exit_code
+# Check if Ktlint found errors
+if [ $ktlint_exit_code -ne 0 ]; then
+    echo "Ktlint found errors. Commit aborted."
+    exit 1
+fi
+# If no errors were found, allow the commit
 exit 0
